### PR TITLE
Create initial support section

### PR DESCRIPTION
**Pull request by tvararu**
### Context

We'd like a support section to contain functionality like:

- Showing TRN Requests
- Showing Emails
- A Performance dashboard
- Sidekiq (just a link, no actual UI since we will use Sidekiq's)
- Auditing
- Showing stored Validation errors

### Changes proposed in this pull request

Mostly the initial boilerplate and `dotenv`.

Needs:

- [x] Two environment variables in the dev/preprod/production environments
- [x] A basic system test

### Guidance to review

image

### Checklist

https://trello.com/c/WEBORP57

- [x] Attach to Trello card
- [x] Rebased master
- [x] Cleaned commit history
- [x] Tested by running locally

### CODE REVIEW

**Comment by benilovj** [comment]
I'm not wild about having this section surfacing PII unless we definitely know we need it, which I'm not sure we do yet.

**Comment by tvararu** [comment]
@benilovj agree, PII removed :+1:

**Comment by fofr** [comment]
Will there be a signed in as/sign out link at the top?

**Comment by tvararu** [comment]
@fofr eventually, currently just with basic auth there is no real "sign out" state...

**Review by felixclack — APPROVED** [review]

**Pull request merged**
